services:
  - type: web
    name: svasth-ol
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
