services:
  - type: web
    name: svasthol
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public,max-age=31536000,immutable
